task:
  name: Mvn Clean Install
  container:
    image: maven:8-jdk
  maven_cache:
    folder: ~/.m2
  test_script: mvn clean install
task:
  name: Mvn Test
  container:
    image: maven:latest
  maven_cache:
    folder: ~/.m2
  test_script: mvn test
